'use strict';
function renderLessonNav(m){const d=LESSONS[m.id];return d?`<nav class="lesson-nav" aria-label="${t(B('En este capítulo','In this chapter'))}">${d.sections.map(s=>`<a href="#${m.id}" data-section="${m.id}-${s.id}">${t(s.title)}</a>`).join('')}<a href="#${m.id}" data-section="${m.id}-practice">${t(B('Ejercicios propuestos','Practice problems'))}</a></nav>`:'';}
function renderExpanded(m){
const d=LESSONS[m.id];if(!d)return '';
const jump=`<nav class="lesson-nav" aria-label="${t(B('En este capítulo','In this chapter'))}">${d.sections.map(s=>`<a href="#${m.id}" data-section="${m.id}-${s.id}">${t(s.title)}</a>`).join('')}<a href="#${m.id}" data-section="${m.id}-practice">${t(B('Ejercicios propuestos','Practice problems'))}</a></nav>`;
const sections=d.sections.map(s=>`<section class="deep-lesson" id="${m.id}-${s.id}" tabindex="-1"><h2>${t(s.title)}</h2>${t(s.body).map(p=>`<p>${p}</p>`).join('')}${s.formula?`<div class="equation">${s.formula}</div>`:''}${m.id==='cap1'?introExtra(s.id):''}${m.id==='cap2'&&s.id==='sectores'?loadProfile():''}</section>`).join('');
const links=m.n===1||m.n===9?[['simulador.html',B('Explorar el simulador','Explore the simulator')]]:m.n===2||m.n===3?[['ejemplos.html',B('Abrir ejemplos y calculadoras','Open examples and calculators')]]:m.n>=7?[['diseno.html',B('Aplicar en el taller de diseño CHEC','Apply in the CHEC design workshop')]]:[];
return `${sections}${d.recovered?`<section class="deep-lesson"><h2>${t(B("Ejemplos originales revisados","Revised original examples"))}</h2>${d.recovered.map(r=>`<article class="problem"><h3>${t(r[0])}</h3><p>${t(r[1])}</p><details><summary>${t(B("Ver solución razonada","Show worked solution"))}</summary><p>${t(r[2])}</p></details></article>`).join('')}</section>`:''}<section class="practice" id="${m.id}-practice" tabindex="-1"><h2>${t(B('Ejercicios propuestos','Practice problems'))}</h2><p>${t(B('Resuelve primero en tu cuaderno. Consulta la pista cuando la necesites y después contrasta el procedimiento.','Solve in your notebook first. Use the hint if needed, then compare your method.'))}</p>${d.exercises.map((e,i)=>`<article class="problem"><h3>${t(B('Problema','Problem'))} ${m.n}.${i+1}</h3><p>${t(e.prompt)}</p><details><summary>${t(B('Ver pista','Show hint'))}</summary><p>${t(e.hint)}</p></details><details><summary>${t(B('Contrastar solución','Check solution'))}</summary><p>${t(e.solution)}</p></details></article>`).join('')}</section>${links.map(([url,label])=>`<p><a class="button light" href="${url}">${t(label)}</a></p>`).join('')}`;
}
function introExtra(id){
if(id==='sistema'){const rows=[
[B('Generación','Generation'),B('Convertir energía primaria en electricidad.','Convert primary energy into electricity.'),B('Según tecnología y conexión.','Depends on technology and connection.'),B('Generadores y autogeneradores.','Generators and self-generators.'),B('Una central puede conectarse a distintos niveles. El rango ilustrativo de salida de una máquina no define un nivel regulatorio de distribución.','A plant may connect at different levels. An illustrative machine output-voltage range does not define a distribution regulatory level.')],
['STN',B('Transporte e interconexión nacional.','National transmission and interconnection.'),'≥220 kV',B('Transmisores nacionales.','National transmission operators.'),B('Distingue la red de transmisión de los activos de conexión y de las redes regionales.','Distinguish transmission from connection assets and regional networks.')],
['STR',B('Transporte regional hacia distribución.','Regional transfer toward distribution.'),B('Nivel 4: 57,5≤V<220 kV.','Level 4: 57.5≤V<220 kV.'),B('Operadores de red.','Distribution network operators.'),B('El ejemplo de 115 kV se sitúa en el nivel 4, no se clasifica automáticamente como STN.','The 115 kV example lies in level 4; it is not automatically classified as STN.')],
['SDL',B('Distribución local hacia los usuarios.','Local distribution to customers.'),B('Niveles 1, 2 y 3.','Levels 1, 2 and 3.'),B('Operadores de red.','Distribution network operators.'),B('Nivel 1: V<1 kV. Nivel 2: 1≤V<30 kV. Nivel 3: 30≤V<57,5 kV. Por ejemplo: 0,208 kV, 13,2 kV y 34,5 kV, respectivamente.','Level 1: V<1 kV. Level 2: 1≤V<30 kV. Level 3: 30≤V<57.5 kV. Examples: 0.208 kV, 13.2 kV and 34.5 kV, respectively.')],
[B('Comercialización','Retailing'),B('Compra, venta y atención comercial.','Purchasing, selling and customer service.'),B('No es un nivel de tensión.','Not a voltage level.'),B('Comercializadores.','Retailers.'),B('Puede ser una actividad de una empresa integrada, pero su función es distinta de operar la infraestructura.','It may belong to an integrated utility, but differs from operating network infrastructure.')]
];return `<div class="table-wrap"><table class="system-table"><caption>${t(B('Funciones del sistema eléctrico','Power-system functions'))}</caption><thead><tr>${t(B(['Actividad / sistema','Función','Tensión / clasificación','Responsable','Detalle'],['Activity / system','Function','Voltage / classification','Responsible party','Details'])).map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.slice(0,4).map((x,i)=>i===0?`<th scope="row">${typeof x==='string'?x:t(x)}</th>`:`<td>${typeof x==='string'?x:t(x)}</td>`).join('')}<td><details><summary>${t(B('Ver más','Read more'))}</summary><p>${t(r[4])}</p></details></td></tr>`).join('')}</tbody></table></div><p class="units">${t(B('Fuente de clasificación:','Classification source:'))} <a href="https://gestornormativo.creg.gov.co/gestor/entorno/docs/resolucion_creg_0015_2018.htm">CREG 015/2018, art. 3</a>.</p>`;}
if(id==='aereas'||id==='subterraneas'){let rows=id==='aereas'?[
[B('Postes y retenidas','Poles and guys'),B('Soportan cargas y transfieren esfuerzos al terreno. Verifica resistencia, altura, cimentación y geometría de retenidas.','Support loads and transfer forces to the ground. Check strength, height, foundations and guy geometry.')],
[B('Conductores','Conductors'),B('Selecciona capacidad térmica, impedancia y características mecánicas. ACSR combina aluminio conductor y refuerzo de acero; no es la única alternativa.','Select thermal capability, impedance and mechanical properties. ACSR combines conductive aluminum with steel reinforcement; it is not the only option.')],
[B('Crucetas y herrajes','Crossarms and fittings'),B('Definen puntos de sujeción, separación y transmisión de fuerzas. Las normas de aisladores no sustituyen las especificaciones de la cruceta.','Define attachment points, separation and load transfer. Insulator standards do not replace crossarm specifications.')],
[B('Aisladores','Insulators'),B('Aportan aislamiento y resistencia mecánica. Considera contaminación, distancia de fuga, sobretensiones y tipo de esfuerzo.','Provide insulation and mechanical strength. Consider pollution, creepage, overvoltage and loading type.')],
[B('Transformadores','Transformers'),B('Relacionan primario y secundario. Selecciona conexión, potencia, impedancia y protección; una lista de capacidades típicas no constituye catálogo aprobado.','Connect primary and secondary circuits. Select connection, rating, impedance and protection; typical sizes are not an approved catalog.')]
]:[
[B('Ductos','Ducts'),B('Alojan cables y condicionan tendido y disipación. Verifica material, diámetro interior, reservas y configuración del banco.','Contain cables and influence pulling and heat dissipation. Verify material, inside diameter, spares and duct-bank configuration.')],
[B('Cables y aislamiento','Cables and insulation'),B('XLPE es polietileno reticulado; EPR es caucho de etileno-propileno. El original confundía ambos materiales. Selecciona tensión de aislamiento, pantalla y accesorios compatibles.','XLPE is cross-linked polyethylene; EPR is ethylene-propylene rubber. The original confused these materials. Select compatible insulation voltage, screens and accessories.')],
[B('Cámaras y empalmes','Vaults and joints'),B('Dimensiona por equipos, radios de curvatura, maniobra y acceso conforme al diseño aplicable. Verifica drenaje y condiciones de trabajo.','Size for equipment, bending radii, operation and access under the applicable design. Check drainage and working conditions.')]
];return `<div class="equipment-list">${rows.map(r=>`<details><summary>${t(r[0])}</summary><p>${t(r[1])}</p></details>`).join('')}</div>`;}
if(id==='comparacion'){const rows=t(B([['Exposición','Vegetación, viento y descargas','Excavación ajena, agua y condiciones del suelo'],['Reparación','Acceso frecuentemente visible','Localización y acceso especializados'],['Expansión','Revisar apoyos y servidumbres','Revisar reservas y obra civil'],['Evaluación económica','Presupuestar el caso real','Presupuestar el caso real; sin factor fijo 3–10×']],[['Exposure','Vegetation, wind and lightning','Third-party excavation, water and soil conditions'],['Repair','Often visible access','Specialized fault location and access'],['Expansion','Check supports and easements','Check spares and civil works'],['Economics','Estimate actual project costs','Estimate actual project costs; no fixed 3–10× multiplier']]));return `<div class="table-wrap"><table class="system-table"><thead><tr><th>${t(B('Criterio','Criterion'))}</th><th>${t(B('Aérea','Overhead'))}</th><th>${t(B('Subterránea','Underground'))}</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
return '';
}
function loadProfile(){const data=[400,380,350,420,710,820,870,850,830,910,780,540];let energy=data.reduce((a,b)=>a+b,0)*2;return `<div class="profile-example"><h3>${t(B('Ejemplo recuperado: doce intervalos de dos horas','Recovered example: twelve two-hour intervals'))}</h3><p>${t(B('Se interpretan los registros como potencias medias de cada intervalo, no como muestras instantáneas.','Read the records as average powers over each interval, not instantaneous samples.'))}</p><button class="button light" data-load-order aria-pressed="false">${t(B("Mostrar curva de duración","Show load-duration curve"))}</button> <a href="datos/perfil-original-2h.csv" download>CSV</a><div class="load-bars" role="img" aria-label="${t(B('Perfil horario:','Time profile:'))} ${data.join(', ')} kW">${data.map((p,i)=>`<div><span style="height:${p/6}px" title="${i*2}–${i*2+2} h: ${p} kW"></span><small>${i*2}h</small></div>`).join('')}</div><details><summary>${t(B('Datos y solución','Data and solution'))}</summary><p>${data.join(', ')} kW.</p><p>E=${energy} kWh; Pmedia=655 kW; Pmax=910 kW; Fᴸ=0,71978; heq=17,2747 h.</p><p>${t(B('Ordena estos valores de mayor a menor para construir la curva de duración. La suma de áreas debe seguir siendo 15 720 kWh.','Sort these values from highest to lowest for the load-duration curve. Total area must remain 15,720 kWh.'))}</p></details></div>`;}
document.addEventListener('click',e=>{const link=e.target.closest('[data-section]');if(!link)return;e.preventDefault();const target=document.getElementById(link.dataset.section);if(target){target.focus({preventScroll:true});target.scrollIntoView({behavior:'auto',block:'start'});}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-load-order]');if(!button)return;const duration=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',duration);button.textContent=t(duration?B('Mostrar orden horario','Show chronological order'):B('Mostrar curva de duración','Show load-duration curve'));const data=[400,380,350,420,710,820,870,850,830,910,780,540];if(duration)data.sort((a,b)=>b-a);const chart=button.parentElement.querySelector('.load-bars');chart.setAttribute('aria-label',t(duration?B('Curva de duración','Load-duration curve'):B('Perfil horario','Time profile'))+': '+data.join(', ')+' kW');chart.querySelectorAll('span').forEach((bar,i)=>{bar.style.height=data[i]/6+'px';bar.title=i*2+'–'+(i*2+2)+' h: '+data[i]+' kW';});});
